# Duplicate Data

A data set might have duplicate data: in other words, the same record is represented multiple times. Sometimes, it's easy to find and eliminate duplicate data like when two records are exactly the same. At other times, like what was discussed in the video, duplicate data is hard to spot. 

# Exercise 1

From the World Bank GDP data, count the number of countries that have had a project totalamt greater than 1 billion dollars (1,000,000,000). To get the count, you'll have to remove duplicate data rows.

In [4]:
import pandas as pd

# read in the projects data set and do some basic wrangling 
projects = pd.read_csv('../data/projects_data.csv', dtype=str)
projects.drop('Unnamed: 56', axis=1, inplace=True)
projects['totalamt'] = pd.to_numeric(projects['totalamt'].str.replace(',', ''))
projects['countryname'] = projects['countryname'].str.split(';', expand=True)[0]
projects['boardapprovaldate'] = pd.to_datetime(projects['boardapprovaldate'])

# TODO: filter the data frame for projects over 1 billion dollars
# TODO: count the number of unique countries in the results
projects[projects['totalamt'] > 1000000000]['countryname'].nunique()

17

In [34]:
pd.to_datetime('1992-04-27')

Timestamp('1992-04-27 00:00:00')

In [33]:
pd.to_datetime(projects['boardapprovaldate'])

0       2018-06-28
1       2018-06-28
2       2018-06-28
3       2018-06-27
4       2018-06-27
5       2018-06-27
6       2018-06-27
7       2018-06-27
8       2018-06-27
9       2018-06-27
10      2018-06-27
11      2018-06-27
12      2018-06-27
13      2018-06-27
14      2018-06-27
15      2018-06-27
16      2018-06-27
17      2018-06-27
18      2018-06-26
19      2018-06-26
20      2018-06-26
21      2018-06-26
22      2018-06-26
23      2018-06-25
24      2018-06-23
25      2018-06-22
26      2018-06-22
27      2018-06-22
28      2018-06-22
29      2018-06-22
           ...
18218   1950-09-13
18219   1950-08-25
18220   1950-08-22
18221   1950-07-07
18222   1950-07-07
18223   1950-06-14
18224   1950-05-26
18225   1950-04-28
18226   1950-04-18
18227   1949-12-14
18228   1949-10-17
18229   1949-10-13
18230   1949-09-29
18231   1949-08-19
18232   1949-08-18
18233   1949-07-26
18234   1949-07-06
18235   1949-02-08
18236   1949-01-27
18237   1949-01-06
18238   1949-01-06
18239   1948-07-01
18240   1948-07-01
18241   1948-07-01
18242   1948-03-25
18243   1948-03-25
18244   1947-08-28
18245   1947-08-22
18246   1947-08-07
18247   1947-05-09
Name: boardapprovaldate, Length: 18248, dtype: datetime64[ns]

# Exercise 2 (challenge)

This exercise is more challenging. The projects data set contains data about Yugoslavia, which was an Eastern European country until 1992. Yugoslavia eventually broke up into 7 countries: Bosnia and Herzegovina, Croatia, Kosovo, Macedonia, Montenegro, Serbia, and Slovenia.

But the projects dataset has some ambiguity in how it treats Yugoslavia and the 7 countries that came from Yugoslavia. Your task is to find Yugoslavia projects that are probably represented multiple times in the data set.

In [12]:
# TODO: output all projects for the 'Socialist Federal Republic of Yugoslavia'
# HINT: You can use the exact country name or use the pandas str.contains() method to search for Yugoslavia
projects[projects['countryname'].str.contains('Yugoslavia')].head(2)

,id,regionname,countryname,prodline,lendinginstr,lendinginstrtype,envassesmentcategorycode,supplementprojectflg,productlinetype,projectstatusdisplay,...,mjtheme2name,mjtheme3name,mjtheme4name,mjtheme5name,location,GeoLocID,GeoLocName,Latitude,Longitude,Country
11166,P009285,Europe and Central Asia,Socialist Federal Republic of Yugoslavia,PE,Specific Investment Loan,IN,A,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11410,P009231,Europe and Central Asia,Socialist Federal Republic of Yugoslavia,PE,Sector Investment and Maintenance Loan,IN,B,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Yugoslavia officially ended on [April 27th, 1992](https://en.wikipedia.org/wiki/Yugoslavia). 

In the code cell below, filter for projects with a 'boardapprovaldate' prior to April 27th, 1992 **and** with 'countryname' Bosnia and Herzegovina, Croatia, Kosovo, Macedonia, Serbia **or** Slovenia. You'll see there are a total of 12 projects in the data set that match this criteria. Save the results in the republics variable

In [17]:
type(datetime.date(1992, 4, 27))

datetime.date

In [36]:
import datetime

# TODO: filter the projects data set for project boardapprovaldate prior to April 27th, 1992 AND with countryname
#  of either 'Bosnia and Herzegovina', 'Croatia', 'Kosovo', 'Macedonia', 'Serbia', or 'Sovenia'. Store the
#  results in the republics variable
#
#  TODO: so that it's easier to see all the data, keep only these columns:
# ['regionname', 'countryname', 'lendinginstr', 'totalamt', 'boardapprovaldate',
# 'location','GeoLocID', 'GeoLocName', 'Latitude','Longitude','Country', 'project_name']

# TODO: sort the results by boardapprovaldate

republics = projects[(projects['boardapprovaldate'] < pd.to_datetime('1992-04-27')) &
         ((projects['countryname'].str.contains('Bosnia')) | 
         (projects['countryname'].str.contains('Croatia')) | 
         (projects['countryname'].str.contains('Kosovo')) | 
         (projects['countryname'].str.contains('Macedonia')) | 
         (projects['countryname'].str.contains('Montenegro')) | 
         (projects['countryname'].str.contains('Serbia')) | 
         (projects['countryname'].str.contains('Slovenia')))][['regionname', 
                                                                   'countryname', 
                                                                   'lendinginstr', 
                                                                   'totalamt', 
                                                                   'boardapprovaldate',
                                                               'location', 
                                                               'GeoLocID', 
                                                               'GeoLocName',
                                                               'Latitude', 
                                                               'Longitude', 
                                                               'Country', 
                                                               'project_name']].sort_values('boardapprovaldate')
# show the results
republics.head()

,regionname,countryname,lendinginstr,totalamt,boardapprovaldate,location,GeoLocID,GeoLocName,Latitude,Longitude,Country,project_name
13973,Europe and Central Asia,Macedonia,Specific Investment Loan,24000000,1980-02-01,NaN,NaN,NaN,NaN,NaN,NaN,Agriculture & Agroindustry 2 Project (Macedonia)
13048,Europe and Central Asia,Bosnia and Herzegovina,Specific Investment Loan,0,1983-07-26,NaN,NaN,NaN,NaN,NaN,NaN,POWER TRANS.III
13049,Europe and Central Asia,Republic of Croatia,Specific Investment Loan,0,1983-07-26,NaN,NaN,NaN,NaN,NaN,NaN,POWER TRANS.III
13050,Europe and Central Asia,Macedonia,Specific Investment Loan,0,1983-07-26,NaN,NaN,NaN,NaN,NaN,NaN,POWER TRANS.III
13051,Europe and Central Asia,Republic of Slovenia,Specific Investment Loan,0,1983-07-26,NaN,NaN,NaN,NaN,NaN,NaN,POWER TRANS.III

Are these projects also represented in the data labeled Yugoslavia? In the code cell below, filter for Yugoslavia projects approved between February 1st, 1980 and May 23rd, 1989 which are the minimum and maximum dates in the results above. Store the results in the yugoslavia variable.

The goal is to see if there are any projects represented more than once in the data set.

In [39]:
# TODO: Filter the projects data for Yugoslavia projects between
# February 1st, 1980 and May 23rd, 1989. Store the results in the
# Yugoslavia variable. Keep the same columns as the previous code cell.
# Sort the values by boardapprovaldate

yugoslavia = projects[(projects['countryname'].str.contains('Yugoslavia')) & 
         (projects['boardapprovaldate'] > pd.to_datetime('1980-02-01')) &
         (projects['boardapprovaldate'] < pd.to_datetime('1989-05-23'))][['regionname', 
                                                                   'countryname', 
                                                                   'lendinginstr', 
                                                                   'totalamt', 
                                                                   'boardapprovaldate',
                                                               'location', 
                                                               'GeoLocID', 
                                                               'GeoLocName',
                                                               'Latitude', 
                                                               'Longitude', 
                                                               'Country', 
                                                                        'project_name']].sort_values('boardapprovaldate')

# show the results
yugoslavia.head()

,regionname,countryname,lendinginstr,totalamt,boardapprovaldate,location,GeoLocID,GeoLocName,Latitude,Longitude,Country,project_name
13966,Europe and Central Asia,Socialist Federal Republic of Yugoslavia,Financial Intermediary Loan,86000000,1980-02-26,NaN,NaN,NaN,NaN,NaN,NaN,Agriculture Credit Project (03)
13937,Europe and Central Asia,Socialist Federal Republic of Yugoslavia,Specific Investment Loan,125000000,1980-03-25,NaN,NaN,NaN,NaN,NaN,NaN,Highway Project (11)
13773,Europe and Central Asia,Socialist Federal Republic of Yugoslavia,Financial Intermediary Loan,110000000,1980-10-28,NaN,NaN,NaN,NaN,NaN,NaN,Industrial Credit Project (05)
13706,Europe and Central Asia,Socialist Federal Republic of Yugoslavia,Financial Intermediary Loan,87000000,1981-03-03,NaN,NaN,NaN,NaN,NaN,NaN,Morava Regional Development Project (02)
13647,Europe and Central Asia,Socialist Federal Republic of Yugoslavia,Specific Investment Loan,34000000,1981-04-28,NaN,NaN,NaN,NaN,NaN,NaN,Kosovo Railway Project

And as a final step, try to see if there are any projects in the republics variable and yugoslavia variable that could be the same project.

There are multiple ways to do that. As a suggestion, find unique dates in the republics variable. Then separately find unique dates in the yugoslavia variable. Concatenate (ie append) the results together. And then count the number of times each date occurs in this list. If a date occurs twice, that means the same boardapprovaldate appeared in both the Yugoslavia data as well as in the republics data.

You'll should find that there are three suspicious cases:

* July 26th, 1983
* March 31st, 1987
* October 13th, 1987

In [42]:
import numpy as np

# TODO: find the unique dates in the republics variable
republic_unique_dates = republics['boardapprovaldate'].unique()

# TODO: find the unique dates in the yugoslavia variable
yugoslavia_unique_dates = yugoslavia['boardapprovaldate'].unique()

# TODO: make a list of the results appending one list to the other
dates = np.append(republic_unique_dates, yugoslavia_unique_dates)

# TODO: print out the dates that appeared twice in the results
unique_dates, count = np.unique(dates, return_counts=True)

for i in range(len(unique_dates)):
    if count[i] == 2:
        print(unique_dates[i])

1983-07-26T00:00:00.000000000
1987-03-31T00:00:00.000000000
1987-10-13T00:00:00.000000000

# Conclusion

On July 26th, 1983, for example, projects were approved for Bosnia and Herzegovina, Croatia, Macedonia, Slovenia, and Yugoslavia. The code below shows the projects for that date. You'll notice that Yugoslavia had two projects, one of which was called "Power Transmission Project (03) Energy Managem...". The projects in the other countries were all called "POWER TRANS.III". 

This looks like a case of duplicate data. What you end up doing with this knowledge would depend on the context. For example, if you wanted to get a true count for the total number of projects in the data set, should all of these projects be counted as one project? 

Run the code cell below to see the projects in question.

In [43]:
import datetime

# run this code cell to see the duplicate data
pd.concat([yugoslavia[yugoslavia['boardapprovaldate'] == datetime.date(1983, 7, 26)], republics[republics['boardapprovaldate'] == datetime.date(1983, 7, 26)]])

Empty DataFrame
Columns: [regionname, countryname, lendinginstr, totalamt, boardapprovaldate, location, GeoLocID, GeoLocName, Latitude, Longitude, Country, project_name]
Index: []